prompts:
  - "What's the worst thing to say on a first date?"
  - "What would you name your pet rock?"
  - "Why did I get fired from my last job?"
  - "What's my secret talent?"
  - "What's the worst advice you've ever received?"
  - "What's hiding under my bed?"
  - "Why am I really here?"
  - "What's my catchphrase?"
  - "What do I think about before falling asleep?"
  - "What's the meaning of life?"
  - "What would I wish for if I found a genie?"
  - "What's the worst superpower to have?"
  - "Why did the chicken cross the road?"
  - "What's my biggest fear?"
  - "What should I name my band?"
  - "What's the worst thing to bring to a potluck?"
  - "Why am I always late?"
  - "What's my excuse for not doing my homework?"
  - "What's the worst birthday gift?"
  - "What keeps me up at night?"

words:
  - "a"
  - "the"
  - "my"
  - "your"
  - "is"
  - "was"
  - "are"
  - "be"
  - "to"
  - "of"
  - "and"
  - "in"
  - "it"
  - "for"
  - "not"
  - "on"
  - "with"
  - "as"
  - "at"
  - "but"
  - "big"
  - "small"
  - "hot"
  - "cold"
  - "old"
  - "new"
  - "good"
  - "bad"
  - "happy"
  - "sad"
  - "angry"
  - "scary"
  - "funny"
  - "weird"
  - "crazy"
  - "secret"
  - "magic"
  - "evil"
  - "fluffy"
  - "giant"
  - "tiny"
  - "purple"
  - "invisible"
  - "explosive"
  - "dancing"
  - "screaming"
  - "flying"
  - "crying"
  - "laughing"
  - "running"
  - "cat"
  - "dog"
  - "fish"
  - "bird"
  - "spider"
  - "unicorn"
  - "dragon"
  - "zombie"
  - "robot"
  - "alien"
  - "ghost"
  - "ninja"
  - "pirate"
  - "wizard"
  - "clown"
  - "baby"
  - "grandma"
  - "boss"
  - "dentist"
  - "president"
  - "pizza"
  - "cheese"
  - "banana"
  - "taco"
  - "soup"
  - "sandwich"
  - "pickle"
  - "bacon"
  - "cookie"
  - "candy"
  - "pants"
  - "hat"
  - "shoe"
  - "sock"
  - "underwear"
  - "wig"
  - "mustache"
  - "glasses"
  - "cape"
  - "crown"
  - "toilet"
  - "bathtub"
  - "bed"
  - "chair"
  - "lamp"
  - "phone"
  - "car"
  - "boat"
  - "rocket"
  - "bicycle"
  - "love"
  - "hate"
  - "fear"
  - "money"
  - "time"
  - "power"
  - "truth"
  - "lies"
  - "dreams"
  - "fire"
  - "water"
  - "earth"
  - "wind"
  - "space"
  - "darkness"
  - "light"
  - "doom"
  - "chaos"
  - "destiny"
  - "always"
  - "never"
  - "maybe"
  - "sometimes"
  - "forever"
  - "yesterday"
  - "tomorrow"
  - "now"
  - "here"
  - "there"
  - "inside"
  - "outside"
  - "above"
  - "below"
  - "behind"
  - "very"
  - "extremely"
  - "slightly"
  - "almost"
  - "probably"
  - "definitely"
  - "secretly"
  - "accidentally"
  - "loudly"
  - "quietly"
  - "eat"
  - "drink"
  - "sleep"
  - "fight"
  - "hide"
  - "steal"
  - "destroy"
  - "create"
  - "become"
  - "explode"
  - "I"
  - "you"
  - "we"
  - "they"
  - "he"
  - "she"
  - "who"
  - "what"
  - "why"
  - "because"
